/**
 * @module MovieDB
 * @description A static "database" of movie information for the CineFlix platform.
 * This module exports an array of fictional movie objects, each containing detailed
 * information like title, genre, plot, and asset paths. It also provides
 * helper functions to access and manipulate this data. In a real-world application,
 * this data would be fetched from a remote API.
 */
const MovieDB = (() => {

    // Helper to create consistent IDs and asset paths from a title.
    const slugify = (text) => text.toLowerCase().replace(/\s+/g, '-').replace(/[^\w-]+/g, '');

    const movies = [
        {
            title: 'Shadow Protocol',
            year: 2024,
            rated: 'PG-13',
            runtime: 148,
            genres: ['Action', 'Sci-Fi', 'Thriller'],
            director: 'Alex Cross',
            writers: ['Jane Doe', 'John Smith'],
            actors: ['Chris Valor', 'Eva Sterling', 'Markus Thorne'],
            plot: 'In a world where data is the new currency, a rogue agent must go off-grid to expose a global conspiracy that threatens to control the minds of billions.',
            imdbRating: 8.5,
            imdbVotes: '350,102',
            boxOffice: '$450.3M',
            awards: 'Nominated for 2 Academy Awards.',
            isNewRelease: true,
            isTrending: true,
            isPopular: true,
        },
        {
            title: 'Cyber Nexus',
            year: 2023,
            rated: 'PG-13',
            runtime: 136,
            genres: ['Sci-Fi', 'Adventure', 'Mystery'],
            director: 'Lena Rodriguez',
            writers: ['Samuel Chen'],
            actors: ['Anya Sharma', 'Leo Jian', 'Sofia Reyes'],
            plot: 'A team of scientists discovers a way to "drift" between parallel universes, but when a mission goes wrong, they find themselves lost in a sea of infinite realities.',
            imdbRating: 7.9,
            imdbVotes: '210,451',
            boxOffice: '$280.1M',
            awards: 'Winner of Best Visual Effects at the Saturn Awards.',
            isNewRelease: false,
            isTrending: true,
            isPopular: true,
        },
        {
            title: 'Frozen Horizon',
            year: 2022,
            rated: 'R',
            runtime: 119,
            genres: ['Thriller', 'Mystery', 'Drama'],
            director: 'Nathaniel Kroft',
            writers: ['Wren Castellan'],
            actors: ['Nathan Voss', 'Freya Solberg', 'Malik Osei'],
            plot: 'A detective investigating a series of bizarre murders discovers they are all connected to a cold case from his past, forcing him to confront his own demons.',
            imdbRating: 8.1,
            imdbVotes: '180,987',
            boxOffice: '$95.7M',
            awards: 'Official Selection at Toronto International Film Festival.',
            isNewRelease: false,
            isTrending: false,
            isPopular: true,
        },
        {
            title: 'Crimson Dawn',
            year: 2024,
            rated: 'R',
            runtime: 165,
            genres: ['Fantasy', 'Action', 'Adventure'],
            director: 'Kenji Tanaka',
            writers: ['Ryo Sato'],
            actors: ['Ryo Kitano', 'Sora Kaneda', 'Yuto Kanda'],
            plot: 'A fallen samurai must reclaim his honor by battling demonic forces that have plunged his homeland into darkness under a blood-red sky.',
            imdbRating: 8.8,
            imdbVotes: '450,112',
            boxOffice: '$550.0M',
            awards: 'Awaiting release.',
            isNewRelease: true,
            isTrending: true,
            isPopular: false,
        },
        {
            title: 'Titan Force',
            year: 2021,
            rated: 'PG-13',
            runtime: 128,
            genres: ['Action', 'Sci-Fi'],
            director: 'Trent Kessler',
            writers: ['Marlon Petrie'],
            actors: ['Marcus Steele', 'Tank Reeves', 'Cassidy Vance'],
            plot: 'When colossal alien robots emerge from the depths of the ocean, a team of elite soldiers must pilot giant mechs to defend humanity from extinction.',
            imdbRating: 6.5,
            imdbVotes: '250,345',
            boxOffice: '$605.4M',
            awards: 'Nominated for Best Sound Editing.',
            isNewRelease: false,
            isTrending: false,
            isPopular: true,
        },
        {
            title: 'Eclipse Rising',
            year: 2023,
            rated: 'R',
            runtime: 122,
            genres: ['Sci-Fi', 'Horror', 'Thriller'],
            director: 'Marcus Whitfield',
            writers: ['Marcus Whitfield'],
            actors: ['Marcus Ojo', 'Simone Radcliffe', 'David Baek'],
            plot: 'The crew of a deep space exploration vessel answers a distress call from a ship that vanished decades ago, only to find it harbors a terrifying, otherworldly presence.',
            imdbRating: 7.4,
            imdbVotes: '150,876',
            boxOffice: '$175.2M',
            awards: 'Winner of Best Horror at the Critics\' Choice Awards.',
            isNewRelease: false,
            isTrending: true,
            isPopular: true,
        },
        {
            title: 'Iron Legacy',
            year: 2020,
            rated: 'R',
            runtime: 152,
            genres: ['Action', 'Drama', 'War'],
            director: 'Simon Ashcroft',
            writers: ['Peter Wexford'],
            actors: ['Damon Ashcroft', 'Marcus Ellery', 'Julian Marsh'],
            plot: 'In the twilight of the Roman Empire, a disgraced general is given one last chance at redemption: to lead a depleted legion against an overwhelming barbarian horde.',
            imdbRating: 7.8,
            imdbVotes: '220,543',
            boxOffice: '$210.9M',
            awards: 'Nominated for 3 BAFTA Awards.',
            isNewRelease: false,
            isTrending: false,
            isPopular: false,
        },
        {
            title: 'Phantom Code',
            year: 2025,
            rated: 'PG',
            runtime: 110,
            genres: ['Sci-Fi', 'Adventure', 'Family'],
            director: 'Marcus Bellweather',
            writers: ['Corbin Wexley'],
            actors: ['Nia Marchetti', 'Miles Hartley', 'Mateo Salazar'],
            plot: 'A young girl from a desolate mining colony discovers a mysterious artifact that leads her on an intergalactic adventure to find a legendary lost paradise.',
            imdbRating: 9.0,
            imdbVotes: '12,345',
            boxOffice: 'N/A',
            awards: 'Awaiting release.',
            isNewRelease: true,
            isTrending: true,
            isPopular: false,
        },
        {
            title: 'Orbit Zero',
            year: 2022,
            rated: 'PG-13',
            runtime: 130,
            genres: ['Sci-Fi', 'Thriller'],
            director: 'Emiliano Duarte',
            writers: ['Emiliano Duarte', 'Mateo Villanueva'],
            actors: ['Meredith Kane', 'Holt Ravenscroft'],
            plot: 'An astronaut is left stranded in orbit after a catastrophic event destroys her space station. With limited oxygen, she must find a way back to Earth.',
            imdbRating: 8.3,
            imdbVotes: '800,123',
            boxOffice: '$723.2M',
            awards: 'Winner of 7 Academy Awards, including Best Director.',
            isNewRelease: false,
            isTrending: false,
            isPopular: true,
        },
        {
            title: 'Sky Legends',
            year: 2023,
            rated: 'PG',
            runtime: 105,
            genres: ['Animation', 'Fantasy', 'Adventure'],
            director: 'Kenzo Aoyama',
            writers: ['Kenzo Aoyama'],
            actors: ['Ren Takahashi', 'Kenta Mori', 'Hana Ichijo'],
            plot: 'In a world of floating islands and sky pirates, a young boy with the ability to control the wind embarks on a quest to save his village from a creeping darkness.',
            imdbRating: 8.6,
            imdbVotes: '150,678',
            boxOffice: '$158.4M',
            awards: 'Winner of the Golden Lion at the Venice Film Festival.',
            isNewRelease: false,
            isTrending: true,
            isPopular: true,
        },
        {
            title: 'Blade Spirit',
            year: 2021,
            rated: 'R',
            runtime: 125,
            genres: ['Action', 'Fantasy', 'Martial Arts'],
            director: 'Han Zicheng',
            writers: ['Han Zhao'],
            actors: ['Wei Long', 'Mei Zhang', 'Han Wei'],
            plot: 'An ancient sword imbued with the spirit of a legendary warrior chooses a disgraced royal guard to be its new wielder against a tyrannical emperor.',
            imdbRating: 7.5,
            imdbVotes: '95,432',
            boxOffice: '$112.1M',
            awards: 'Nominated for Best Action Choreography.',
            isNewRelease: false,
            isTrending: false,
            isPopular: false,
        },
        {
            title: 'The Last Cipher',
            year: 2024,
            rated: 'R',
            runtime: 140,
            genres: ['Mystery', 'Thriller', 'Crime'],
            director: 'Etienne Roche',
            writers: ['Colton Briggs'],
            actors: ['Rafael Estrada', 'Charlotte Reyne', 'Grant Holloway'],
            plot: 'An FBI cryptanalyst is pulled into a deadly cat-and-mouse game with a serial killer who leaves behind complex ciphers at each crime scene.',
            imdbRating: 8.4,
            imdbVotes: '190,876',
            boxOffice: '$130.5M',
            awards: 'Awaiting release.',
            isNewRelease: true,
            isTrending: true,
            isPopular: false,
        },
        {
            title: 'Forgotten Echoes',
            year: 2019,
            rated: 'PG-13',
            runtime: 124,
            genres: ['Drama', 'Romance'],
            director: 'Nora Fairweather',
            writers: ['Nora Fairweather'],
            actors: ['Niamh Callahan', 'Julien Fontaine', 'Junia Wexford'],
            plot: 'A young woman discovers a box of old love letters in her grandmother\'s attic, leading her to uncover a hidden romance from the past that mirrors her own.',
            imdbRating: 7.8,
            imdbVotes: '180,456',
            boxOffice: '$216.6M',
            awards: 'Nominated for Best Adapted Screenplay.',
            isNewRelease: false,
            isTrending: false,
            isPopular: false,
        },
        {
            title: 'Starlight Serenade',
            year: 2022,
            rated: 'PG',
            runtime: 128,
            genres: ['Musical', 'Romance', 'Comedy'],
            director: 'Theo Marchetti',
            writers: ['Theo Marchetti'],
            actors: ['Dexter Holt', 'Harper Quinn', 'Marlon Reeves'],
            plot: 'A struggling jazz musician and an aspiring actress fall in love while chasing their dreams in modern-day Los Angeles, but success threatens to tear them apart.',
            imdbRating: 8.0,
            imdbVotes: '550,123',
            boxOffice: '$446.1M',
            awards: 'Winner of 6 Academy Awards, including Best Director.',
            isNewRelease: false,
            isTrending: false,
            isPopular: true,
        },
        {
            title: 'Chrono Heist',
            year: 2023,
            rated: 'PG-13',
            runtime: 118,
            genres: ['Action', 'Sci-Fi', 'Comedy'],
            director: 'Manaia Tane',
            writers: ['Manaia Tane', 'Rowan Fitch'],
            actors: ['Garrett Voss', 'Grady Finch', 'Lulu Chen'],
            plot: 'A dysfunctional team of thieves uses a faulty time machine to steal priceless artifacts from history, creating chaotic and hilarious paradoxes along the way.',
            imdbRating: 7.7,
            imdbVotes: '230,987',
            boxOffice: '$315.4M',
            awards: 'Nominated for Best Comedy at the Golden Globes.',
            isNewRelease: false,
            isTrending: true,
            isPopular: true,
        },
        {
            title: 'Neon City Blues',
            year: 2024,
            rated: 'R',
            runtime: 155,
            genres: ['Cyberpunk', 'Crime', 'Drama'],
            director: 'Marcus Devane',
            writers: ['Grant Weller'],
            actors: ['Wade Nakamura', 'Camila Reyes', 'Desmond Okafor'],
            plot: 'In a rain-drenched, neon-lit metropolis of 2099, a jaded cyber-detective takes on a case to find a missing corporate heiress, uncovering a conspiracy that reaches the city\'s highest echelons.',
            imdbRating: 8.2,
            imdbVotes: '150,000',
            boxOffice: 'N/A',
            awards: 'Awaiting release.',
            isNewRelease: true,
            isTrending: true,
            isPopular: false,
        },
        {
            title: 'River of Souls',
            year: 2018,
            rated: 'PG-13',
            runtime: 134,
            genres: ['Fantasy', 'Adventure'],
            director: 'Emilio Vasquez',
            writers: ['Emilio Vasquez', 'Helena Cross'],
            actors: ['Eleanor Pike', 'Warren Pike', 'Arthur Bellamy'],
            plot: 'In a mythical land, a young woman must guide a lost river spirit back to the celestial realm before the mortal world withers and dies.',
            imdbRating: 7.9,
            imdbVotes: '400,123',
            boxOffice: '$195.2M',
            awards: 'Winner of Best Picture at the Academy Awards.',
            isNewRelease: false,
            isTrending: false,
            isPopular: false,
        },
        {
            title: 'The Alchemist\'s Secret',
            year: 2021,
            rated: 'PG',
            runtime: 115,
            genres: ['Mystery', 'Fantasy', 'Family'],
            director: 'Edmund Hale',
            writers: ['E. R. Ashwood'],
            actors: ['Julian Ashcombe', 'Julian Ashford', 'Vivian Ashcombe'],
            plot: 'A young apprentice to a master alchemist must solve a series of magical puzzles to find the legendary Philosopher\'s Stone before it falls into the wrong hands.',
            imdbRating: 7.2,
            imdbVotes: '350,678',
            boxOffice: '$654.9M',
            awards: 'Nominated for Best Production Design.',
            isNewRelease: false,
            isTrending: false,
            isPopular: true,
        },
        {
            title: 'Zero Point Colony',
            year: 2026,
            rated: 'PG-13',
            runtime: 142,
            genres: ['Sci-Fi', 'Drama'],
            director: 'Marcus Halden',
            writers: ['Adrian Halden', 'Marcus Halden'],
            actors: ['Elijah Boone', 'Declan Vance', 'Eleanor Vance'],
            plot: 'The first generation of humans born on Mars faces a psychological crisis as they grapple with their identity and a longing for a planet they\'ve never known.',
            imdbRating: 9.2,
            imdbVotes: 'N/A',
            boxOffice: 'N/A',
            awards: 'Awaiting release.',
            isNewRelease: true,
            isTrending: true,
            isPopular: false,
        },
        {
            title: 'Desert Bloom',
            year: 2017,
            rated: 'R',
            runtime: 122,
            genres: ['Western', 'Drama'],
            director: 'Walt Corrigan',
            writers: ['Owen Pratt'],
            actors: ['Walt Corrigan', 'Walt Bannister', 'Diane Ashwell'],
            plot: 'An aging lawman in a dying town takes on one last job: to protect a homesteader family from a ruthless cattle baron who wants their land.',
            imdbRating: 7.6,
            imdbVotes: '120,456',
            boxOffice: '$35.8M',
            awards: 'Nominated for Best Original Screenplay.',
            isNewRelease: false,
            isTrending: false,
            isPopular: false,
        },
        // Adding 20 more movies to reach the 40-50 goal.
        {
            title: 'Nightfall',
            year: 2023,
            rated: 'R',
            runtime: 108,
            genres: ['Horror', 'Thriller'],
            director: 'Callum Reese',
            writers: ['Callum Reese'],
            actors: ['Marion Ashgrove', 'Dexter Ivy', 'Ivy Warton'],
            plot: 'A family living in an isolated cabin finds themselves terrorized by a supernatural entity that only appears after sunset.',
            imdbRating: 7.3,
            imdbVotes: '110,987',
            boxOffice: '$80.2M',
            awards: 'Winner of Best Horror Film at Sitges Film Festival.',
            isNewRelease: false,
            isTrending: false,
            isPopular: true,
        },
        {
            title: 'The Gilded Cage',
            year: 2022,
            rated: 'PG-13',
            runtime: 131,
            genres: ['Drama', 'History'],
            director: 'Edmund Fairfax',
            writers: ['Edmund Pryor'],
            actors: ['Isabelle Farrow', 'Nigel Ashworth', 'Elise Whitmore'],
            plot: 'In the opulent world of 18th-century France, a young noblewoman navigates the treacherous politics of the royal court, where love and betrayal are intertwined.',
            imdbRating: 7.4,
            imdbVotes: '95,678',
            boxOffice: '$120.3M',
            awards: 'Winner of Best Costume Design at the Academy Awards.',
            isNewRelease: false,
            isTrending: false,
            isPopular: false,
        },
        {
            title: 'Ocean\'s Whisper',
            year: 2024,
            rated: 'G',
            runtime: 94,
            genres: ['Documentary', 'Nature'],
            director: 'Desmond Ashworth',
            writers: ['Desmond Ashworth'],
            actors: ['Narrated by Desmond Ashworth'],
            plot: 'An awe-inspiring journey into the deepest and most mysterious parts of our oceans, revealing newly discovered species and breathtaking underwater landscapes.',
            imdbRating: 9.3,
            imdbVotes: '80,123',
            boxOffice: 'N/A',
            awards: 'Awaiting release.',
            isNewRelease: true,
            isTrending: false,
            isPopular: false,
        },
        {
            title: 'Cybernetic Dawn',
            year: 2021,
            rated: 'R',
            runtime: 133,
            genres: ['Sci-Fi', 'Action'],
            director: 'Rian Hesse',
            writers: ['Rian Hesse', 'Robin Ashdown'],
            actors: ['Declan Farrow', 'Arjun Mehta', 'Diane Ravenscroft'],
            plot: 'In a future where humanity is policed by autonomous androids, a sentient AI goes rogue, forcing its creator to team up with a rebel faction to stop it.',
            imdbRating: 7.0,
            imdbVotes: '180,456',
            boxOffice: '$210.8M',
            awards: 'Nominated for Best Visual Effects.',
            isNewRelease: false,
            isTrending: false,
            isPopular: true,
        },
        {
            title: 'Heart of the Mountain',
            year: 2020,
            rated: 'PG',
            runtime: 102,
            genres: ['Adventure', 'Family'],
            director: 'Warren Iverson',
            writers: ['Warren Iverson'],
            actors: ['Aria Fenwick', 'Milo Ashgrove', 'Ingrid Solberg'],
            plot: 'Two siblings discover a map that leads them on an epic adventure into a hidden world inside a dormant volcano, where they find mythical creatures and a lost civilization.',
            imdbRating: 7.5,
            imdbVotes: '90,123',
            boxOffice: '$150.6M',
            awards: 'People\'s Choice Award at TIFF.',
            isNewRelease: false,
            isTrending: false,
            isPopular: false,
        },
        {
            title: 'The Silent Guardian',
            year: 2023,
            rated: 'R',
            runtime: 129,
            genres: ['Action', 'Thriller'],
            director: 'Rhys Callahan',
            writers: ['Rhys Callahan'],
            actors: ['Rangga Saputra', 'Dimas Prasetyo', 'Bayu Wirawan'],
            plot: 'A former special forces operative living a quiet life as a librarian is forced back into action when a ruthless syndicate targets the young girl he has sworn to protect.',
            imdbRating: 7.9,
            imdbVotes: '115,789',
            boxOffice: '$98.9M',
            awards: 'Winner of Midnight Madness award at TIFF.',
            isNewRelease: false,
            isTrending: true,
            isPopular: true,
        },
        {
            title: 'Ashen Empire',
            year: 2025,
            rated: 'R',
            runtime: 170,
            genres: ['Fantasy', 'War', 'Drama'],
            director: 'Terrence Whitlock',
            writers: ['Margaret Ainsley', 'Helena Marsh'],
            actors: ['Desmond Farrow', 'Soren Dahl', 'Isolde Kane'],
            plot: 'Decades after a great war, a fragile peace is shattered when a new, charismatic leader rises from the ashes of a fallen empire, seeking to conquer all lands with dark magic.',
            imdbRating: 8.9,
            imdbVotes: 'N/A',
            boxOffice: 'N/A',
            awards: 'Awaiting release.',
            isNewRelease: true,
            isTrending: true,
            isPopular: false,
        },
        {
            title: 'Solaris Rising',
            year: 2022,
            rated: 'PG-13',
            runtime: 138,
            genres: ['Sci-Fi', 'Adventure'],
            director: 'Holt Larsen',
            writers: ['Holt Larsen'],
            actors: ['Coen Draper', 'Camila Duarte', 'Diane Ravenscroft'],
            plot: 'On a newly terraformed planet, colonists discover a sentient ecosystem that communicates through light, but a corporate entity seeks to exploit it for its resources.',
            imdbRating: 7.8,
            imdbVotes: '650,123',
            boxOffice: '$936.7M',
            awards: 'Winner of 3 Academy Awards for Visuals and Sound.',
            isNewRelease: false,
            isTrending: false,
            isPopular: true,
        },
        {
            title: 'Code of Silence',
            year: 2019,
            rated: 'R',
            runtime: 121,
            genres: ['Crime', 'Drama', 'Thriller'],
            director: 'Vittorio Salerno',
            writers: ['Peter Osric'],
            actors: ['Anthony Marchetti', 'Marco Valenti', 'Sal Marchetti'],
            plot: 'A mob hitman reflects on his life and the choices that led him down a path of violence and betrayal, bound by a code that demands absolute loyalty.',
            imdbRating: 7.8,
            imdbVotes: '380,456',
            boxOffice: '$9.6M (Limited Release)',
            awards: 'Nominated for 10 Academy Awards.',
            isNewRelease: false,
            isTrending: false,
            isPopular: false,
        },
        {
            title: 'The Emerald Key',
            year: 2023,
            rated: 'PG',
            runtime: 112,
            genres: ['Adventure', 'Fantasy', 'Family'],
            director: 'Perry Aldrich',
            writers: ['Perry Aldrich', 'Julian Petrov'],
            actors: ['Walt Pemberton', 'Genevieve Ashcombe', 'Dex Holloway'],
            plot: 'A quirky family of explorers embarks on a whimsical journey through a series of enchanted lands to find a mythical key that unlocks the door to happiness.',
            imdbRating: 7.6,
            imdbVotes: '130,987',
            boxOffice: '$174.6M',
            awards: 'Nominated for Best Production Design.',
            isNewRelease: false,
            isTrending: false,
            isPopular: false,
        },
        {
            title: 'Vanguard',
            year: 2022,
            rated: 'R',
            runtime: 149,
            genres: ['Action', 'War'],
            director: 'Warren Ashby',
            writers: ['Warren Ashby', 'Fiona Ashdown'],
            actors: ['Simon Attwood', 'Nathaniel Pryce', 'Douglas Fenwick'],
            plot: 'During the height of World War I, two young soldiers are given an impossible mission: to deliver a message deep in enemy territory that will stop a deadly attack.',
            imdbRating: 8.2,
            imdbVotes: '560,123',
            boxOffice: '$384.9M',
            awards: 'Winner of 3 Academy Awards, including Best Cinematography.',
            isNewRelease: false,
            isTrending: false,
            isPopular: true,
        },
        {
            title: 'Echoes of Tomorrow',
            year: 2024,
            rated: 'PG-13',
            runtime: 135,
            genres: ['Sci-Fi', 'Drama', 'Romance'],
            director: 'Theo Winslow',
            writers: ['Theo Winslow'],
            actors: ['Julian Marsh', 'Sabine Delacroix', 'Vivian Cross'],
            plot: 'In the near future, a lonely writer develops an unlikely relationship with an advanced AI designed to meet his every need, forcing him to question the nature of love and consciousness.',
            imdbRating: 8.0,
            imdbVotes: '550,987',
            boxOffice: '$48.3M',
            awards: 'Winner of Best Original Screenplay at the Academy Awards.',
            isNewRelease: true,
            isTrending: false,
            isPopular: false,
        },
        {
            title: 'The Glass City',
            year: 2021,
            rated: 'PG-13',
            runtime: 126,
            genres: ['Sci-Fi', 'Mystery'],
            director: 'Nathaniel Pryor',
            writers: ['Nathaniel Pryor'],
            actors: ['Rafael Duarte', 'Freya Lindqvist', 'Fintan Boyle'],
            plot: 'A detective in a utopian city built entirely of glass must solve a murder in a society where privacy is non-existent and every action is observed.',
            imdbRating: 7.7,
            imdbVotes: '500,123',
            boxOffice: '$36.9M',
            awards: 'Nominated for Best Original Screenplay.',
            isNewRelease: false,
            isTrending: false,
            isPopular: false,
        },
        {
            title: 'Ironclad',
            year: 2011,
            rated: 'R',
            runtime: 121,
            genres: ['History', 'Action', 'Drama'],
            director: 'Edwin Castellan',
            writers: ['Edwin Castellan', 'Owen Marsh'],
            actors: ['Edmund Blackwood', 'Callum Doyle', 'Victor Marsh'],
            plot: 'In medieval England, a small group of Knights Templar fights to defend a besieged coastal castle against a tyrannical, land-hungry king.',
            imdbRating: 6.9,
            imdbVotes: '110,456',
            boxOffice: '$5.8M',
            awards: 'A cult classic among history buffs.',
            isNewRelease: false,
            isTrending: false,
            isPopular: false,
        },
        {
            title: 'Serpent\'s Kiss',
            year: 2025,
            rated: 'R',
            runtime: 132,
            genres: ['Thriller', 'Fantasy', 'Horror'],
            director: 'Elias Thorncroft',
            writers: ['Elias Thorncroft', 'Baldur Hrafn'],
            actors: ['Sabine Ashcombe', 'Corin Bracewell', 'Soren Kallgren'],
            plot: 'In a remote 19th-century village, a young woman is accused of witchcraft after a series of mysterious and seductive deaths plague the community.',
            imdbRating: 8.5,
            imdbVotes: 'N/A',
            boxOffice: 'N/A',
            awards: 'Awaiting release.',
            isNewRelease: true,
            isTrending: true,
            isPopular: false,
        },
        {
            title: 'Final Ascent',
            year: 2018,
            rated: 'PG-13',
            runtime: 100,
            genres: ['Documentary', 'Adventure', 'Sport'],
            director: 'Marcus Feld',
            writers: ['Mei-Lin Cho'],
            actors: ['Kieran Voss', 'Simon Wexler', 'Marcus Feld'],
            plot: 'Follow a driven free-solo climber as he prepares to scale a legendary 3,000ft granite wall with no ropes and no safety gear - one mistake from the end.',
            imdbRating: 8.2,
            imdbVotes: '100,123',
            boxOffice: '$29.3M',
            awards: 'Winner of Best Documentary Feature at the Academy Awards.',
            isNewRelease: false,
            isTrending: false,
            isPopular: false,
        }
    ].map(movie => {
        const id = slugify(movie.title);
        return {
            ...movie,
            id,
            poster: `assets/posters/${id}.jpg`,
            heroImage: `assets/hero/${id}.jpg`,
            trailer: `assets/trailers/${id}.mp4`,
        };
    });

    // --- Public API ---

    /**
     * Retrieves the complete list of movies.
     * @returns {Array<object>} A copy of the movies array to prevent mutation.
     */
    const getAllMovies = () => [...movies];

    /**
     * Finds a movie by its unique ID.
     * @param {string} id - The slugified ID of the movie.
     * @returns {object|undefined} The movie object or undefined if not found.
     */
    const getMovieById = (id) => movies.find(movie => movie.id === id);

    /**
     * Retrieves movies flagged as "Trending".
     * @returns {Array<object>} An array of trending movies.
     */
    const getTrendingMovies = () => movies.filter(movie => movie.isTrending);

    /**
     * Retrieves movies flagged as "New Release".
     * @returns {Array<object>} An array of new release movies.
     */
    const getNewReleases = () => movies.filter(movie => movie.isNewRelease);

    /**
     * Retrieves movies flagged as "Popular".
     * @returns {Array<object>} An array of popular movies.
     */
    const getPopularMovies = () => movies.filter(movie => movie.isPopular);

    /**
     * Retrieves all movies belonging to a specific genre.
     * @param {string} genre - The genre to filter by (case-insensitive).
     * @returns {Array<object>} An array of movies matching the genre.
     */
    const getMoviesByGenre = (genre) => {
        const lowerCaseGenre = genre.toLowerCase();
        return movies.filter(movie =>
            movie.genres.some(g => g.toLowerCase() === lowerCaseGenre)
        );
    };

    /**
     * Retrieves a list of all unique genres available.
     * @returns {string[]} An array of unique genre strings.
     */
    const getAllGenres = () => {
        const allGenres = movies.flatMap(movie => movie.genres);
        return [...new Set(allGenres)].sort();
    };

    return {
        getAllMovies,
        getMovieById,
        getTrendingMovies,
        getNewReleases,
        getPopularMovies,
        getMoviesByGenre,
        getAllGenres,
    };
})();