/**
 * @module MovieDB
 * @description A static "database" of movie information for the CineFlix platform.
 * This module exports an array of fictional movie objects, each containing detailed
 * information like title, genre, plot, and asset paths. It also provides
 * helper functions to access and manipulate this data. In a real-world application,
 * this data would be fetched from a remote API.
 */
const MovieDB = (() => {

    // Helper to create consistent IDs and asset paths from a title.
    const slugify = (text) => text.toLowerCase().replace(/\s+/g, '-').replace(/[^\w-]+/g, '');

    const movies = [
        {
            title: 'Shadow Protocol',
            year: 2024,
            rated: 'PG-13',
            runtime: 148,
            genres: ['Action', 'Sci-Fi', 'Thriller'],
            director: 'Alex Cross',
            writers: ['Jane Doe', 'John Smith'],
            actors: ['Chris Valor', 'Eva Sterling', 'Markus Thorne'],
            plot: 'In a world where data is the new currency, a rogue agent must go off-grid to expose a global conspiracy that threatens to control the minds of billions.',
            imdbRating: 8.5,
            imdbVotes: '350,102',
            boxOffice: '$450.3M',
            awards: 'Nominated for 2 Academy Awards.',
            isNewRelease: true,
            isTrending: true,
            isPopular: true,
        },
        {
            title: 'Quantum Drift',
            year: 2023,
            rated: 'PG-13',
            runtime: 136,
            genres: ['Sci-Fi', 'Adventure', 'Mystery'],
            director: 'Lena Rodriguez',
            writers: ['Samuel Chen'],
            actors: ['Anya Sharma', 'Leo Jian', 'Sofia Reyes'],
            plot: 'A team of scientists discovers a way to "drift" between parallel universes, but when a mission goes wrong, they find themselves lost in a sea of infinite realities.',
            imdbRating: 7.9,
            imdbVotes: '210,451',
            boxOffice: '$280.1M',
            awards: 'Winner of Best Visual Effects at the Saturn Awards.',
            isNewRelease: false,
            isTrending: true,
            isPopular: true,
        },
        {
            title: 'Echo Point',
            year: 2022,
            rated: 'R',
            runtime: 119,
            genres: ['Thriller', 'Mystery', 'Drama'],
            director: 'David Fincher',
            writers: ['Gillian Flynn'],
            actors: ['Jake Gyllenhaal', 'Rebecca Ferguson', 'Idris Elba'],
            plot: 'A detective investigating a series of bizarre murders discovers they are all connected to a cold case from his past, forcing him to confront his own demons.',
            imdbRating: 8.1,
            imdbVotes: '180,987',
            boxOffice: '$95.7M',
            awards: 'Official Selection at Toronto International Film Festival.',
            isNewRelease: false,
            isTrending: false,
            isPopular: true,
        },
        {
            title: 'Crimson Dawn',
            year: 2024,
            rated: 'R',
            runtime: 165,
            genres: ['Fantasy', 'Action', 'Adventure'],
            director: 'Kenji Tanaka',
            writers: ['Ryo Sato'],
            actors: ['Hiroyuki Sanada', 'Rinko Kikuchi', 'Tadanobu Asano'],
            plot: 'A fallen samurai must reclaim his honor by battling demonic forces that have plunged his homeland into darkness under a blood-red sky.',
            imdbRating: 8.8,
            imdbVotes: '450,112',
            boxOffice: '$550.0M',
            awards: 'Awaiting release.',
            isNewRelease: true,
            isTrending: true,
            isPopular: false,
        },
        {
            title: 'Titan Force',
            year: 2021,
            rated: 'PG-13',
            runtime: 128,
            genres: ['Action', 'Sci-Fi'],
            director: 'Michael Bay',
            writers: ['Ehren Kruger'],
            actors: ['Dwayne Johnson', 'John Cena', 'Alexandra Daddario'],
            plot: 'When colossal alien robots emerge from the depths of the ocean, a team of elite soldiers must pilot giant mechs to defend humanity from extinction.',
            imdbRating: 6.5,
            imdbVotes: '250,345',
            boxOffice: '$605.4M',
            awards: 'Nominated for Best Sound Editing.',
            isNewRelease: false,
            isTrending: false,
            isPopular: true,
        },
        {
            title: 'Black Horizon',
            year: 2023,
            rated: 'R',
            runtime: 122,
            genres: ['Sci-Fi', 'Horror', 'Thriller'],
            director: 'Jordan Peele',
            writers: ['Jordan Peele'],
            actors: ['Daniel Kaluuya', 'Keke Palmer', 'Steven Yeun'],
            plot: 'The crew of a deep space exploration vessel answers a distress call from a ship that vanished decades ago, only to find it harbors a terrifying, otherworldly presence.',
            imdbRating: 7.4,
            imdbVotes: '150,876',
            boxOffice: '$175.2M',
            awards: 'Winner of Best Horror at the Critics\' Choice Awards.',
            isNewRelease: false,
            isTrending: true,
            isPopular: true,
        },
        {
            title: 'Iron Legacy',
            year: 2020,
            rated: 'R',
            runtime: 152,
            genres: ['Action', 'Drama', 'War'],
            director: 'Ridley Scott',
            writers: ['John Logan'],
            actors: ['Russell Crowe', 'Adam Driver', 'Joaquin Phoenix'],
            plot: 'In the twilight of the Roman Empire, a disgraced general is given one last chance at redemption: to lead a depleted legion against an overwhelming barbarian horde.',
            imdbRating: 7.8,
            imdbVotes: '220,543',
            boxOffice: '$210.9M',
            awards: 'Nominated for 3 BAFTA Awards.',
            isNewRelease: false,
            isTrending: false,
            isPopular: false,
        },
        {
            title: 'Nova Prime',
            year: 2025,
            rated: 'PG',
            runtime: 110,
            genres: ['Sci-Fi', 'Adventure', 'Family'],
            director: 'Jon Favreau',
            writers: ['Justin Theroux'],
            actors: ['Zendaya', 'Tom Holland', 'Jacob Batalon'],
            plot: 'A young girl from a desolate mining colony discovers a mysterious artifact that leads her on an intergalactic adventure to find a legendary lost paradise.',
            imdbRating: 9.0,
            imdbVotes: '12,345',
            boxOffice: 'N/A',
            awards: 'Awaiting release.',
            isNewRelease: true,
            isTrending: true,
            isPopular: false,
        },
        {
            title: 'Orbit Zero',
            year: 2022,
            rated: 'PG-13',
            runtime: 130,
            genres: ['Sci-Fi', 'Thriller'],
            director: 'Alfonso Cuarón',
            writers: ['Alfonso Cuarón', 'Jonás Cuarón'],
            actors: ['Sandra Bullock', 'George Clooney'],
            plot: 'An astronaut is left stranded in orbit after a catastrophic event destroys her space station. With limited oxygen, she must find a way back to Earth.',
            imdbRating: 8.3,
            imdbVotes: '800,123',
            boxOffice: '$723.2M',
            awards: 'Winner of 7 Academy Awards, including Best Director.',
            isNewRelease: false,
            isTrending: false,
            isPopular: true,
        },
        {
            title: 'Sky Legends',
            year: 2023,
            rated: 'PG',
            runtime: 105,
            genres: ['Animation', 'Fantasy', 'Adventure'],
            director: 'Hayao Miyazaki',
            writers: ['Hayao Miyazaki'],
            actors: ['Soma Santoki', 'Masaki Suda', 'Ko Shibasaki'],
            plot: 'In a world of floating islands and sky pirates, a young boy with the ability to control the wind embarks on a quest to save his village from a creeping darkness.',
            imdbRating: 8.6,
            imdbVotes: '150,678',
            boxOffice: '$158.4M',
            awards: 'Winner of the Golden Lion at the Venice Film Festival.',
            isNewRelease: false,
            isTrending: true,
            isPopular: true,
        },
        {
            title: 'Blade Spirit',
            year: 2021,
            rated: 'R',
            runtime: 125,
            genres: ['Action', 'Fantasy', 'Martial Arts'],
            director: 'Zhang Yimou',
            writers: ['Wang Bin'],
            actors: ['Donnie Yen', 'Michelle Yeoh', 'Jet Li'],
            plot: 'An ancient sword imbued with the spirit of a legendary warrior chooses a disgraced royal guard to be its new wielder against a tyrannical emperor.',
            imdbRating: 7.5,
            imdbVotes: '95,432',
            boxOffice: '$112.1M',
            awards: 'Nominated for Best Action Choreography.',
            isNewRelease: false,
            isTrending: false,
            isPopular: false,
        },
        {
            title: 'The Last Cipher',
            year: 2024,
            rated: 'R',
            runtime: 140,
            genres: ['Mystery', 'Thriller', 'Crime'],
            director: 'Denis Villeneuve',
            writers: ['Taylor Sheridan'],
            actors: ['Benicio Del Toro', 'Emily Blunt', 'Josh Brolin'],
            plot: 'An FBI cryptanalyst is pulled into a deadly cat-and-mouse game with a serial killer who leaves behind complex ciphers at each crime scene.',
            imdbRating: 8.4,
            imdbVotes: '190,876',
            boxOffice: '$130.5M',
            awards: 'Awaiting release.',
            isNewRelease: true,
            isTrending: true,
            isPopular: false,
        },
        {
            title: 'Forgotten Echoes',
            year: 2019,
            rated: 'PG-13',
            runtime: 124,
            genres: ['Drama', 'Romance'],
            director: 'Greta Gerwig',
            writers: ['Greta Gerwig'],
            actors: ['Saoirse Ronan', 'Timothée Chalamet', 'Florence Pugh'],
            plot: 'A young woman discovers a box of old love letters in her grandmother\'s attic, leading her to uncover a hidden romance from the past that mirrors her own.',
            imdbRating: 7.8,
            imdbVotes: '180,456',
            boxOffice: '$216.6M',
            awards: 'Nominated for Best Adapted Screenplay.',
            isNewRelease: false,
            isTrending: false,
            isPopular: false,
        },
        {
            title: 'Starlight Serenade',
            year: 2022,
            rated: 'PG',
            runtime: 128,
            genres: ['Musical', 'Romance', 'Comedy'],
            director: 'Damien Chazelle',
            writers: ['Damien Chazelle'],
            actors: ['Ryan Gosling', 'Emma Stone', 'John Legend'],
            plot: 'A struggling jazz musician and an aspiring actress fall in love while chasing their dreams in modern-day Los Angeles, but success threatens to tear them apart.',
            imdbRating: 8.0,
            imdbVotes: '550,123',
            boxOffice: '$446.1M',
            awards: 'Winner of 6 Academy Awards, including Best Director.',
            isNewRelease: false,
            isTrending: false,
            isPopular: true,
        },
        {
            title: 'Chrono Heist',
            year: 2023,
            rated: 'PG-13',
            runtime: 118,
            genres: ['Action', 'Sci-Fi', 'Comedy'],
            director: 'Taika Waititi',
            writers: ['Taika Waititi', 'Jemaine Clement'],
            actors: ['Chris Hemsworth', 'Ryan Reynolds', 'Awkwafina'],
            plot: 'A dysfunctional team of thieves uses a faulty time machine to steal priceless artifacts from history, creating chaotic and hilarious paradoxes along the way.',
            imdbRating: 7.7,
            imdbVotes: '230,987',
            boxOffice: '$315.4M',
            awards: 'Nominated for Best Comedy at the Golden Globes.',
            isNewRelease: false,
            isTrending: true,
            isPopular: true,
        },
        {
            title: 'Neon City Blues',
            year: 2024,
            rated: 'R',
            runtime: 155,
            genres: ['Cyberpunk', 'Crime', 'Drama'],
            director: 'Chad Stahelski',
            writers: ['Derek Kolstad'],
            actors: ['Keanu Reeves', 'Ana de Armas', 'Laurence Fishburne'],
            plot: 'In a rain-drenched, neon-lit metropolis of 2099, a jaded cyber-detective takes on a case to find a missing corporate heiress, uncovering a conspiracy that reaches the city\'s highest echelons.',
            imdbRating: 8.2,
            imdbVotes: '150,000',
            boxOffice: 'N/A',
            awards: 'Awaiting release.',
            isNewRelease: true,
            isTrending: true,
            isPopular: false,
        },
        {
            title: 'River of Souls',
            year: 2018,
            rated: 'PG-13',
            runtime: 134,
            genres: ['Fantasy', 'Adventure'],
            director: 'Guillermo del Toro',
            writers: ['Guillermo del Toro', 'Vanessa Taylor'],
            actors: ['Sally Hawkins', 'Michael Shannon', 'Richard Jenkins'],
            plot: 'In a mythical land, a young woman must guide a lost river spirit back to the celestial realm before the mortal world withers and dies.',
            imdbRating: 7.9,
            imdbVotes: '400,123',
            boxOffice: '$195.2M',
            awards: 'Winner of Best Picture at the Academy Awards.',
            isNewRelease: false,
            isTrending: false,
            isPopular: false,
        },
        {
            title: 'The Alchemist\'s Secret',
            year: 2021,
            rated: 'PG',
            runtime: 115,
            genres: ['Mystery', 'Fantasy', 'Family'],
            director: 'Chris Columbus',
            writers: ['J.K. Rowling'],
            actors: ['Eddie Redmayne', 'Jude Law', 'Katherine Waterston'],
            plot: 'A young apprentice to a master alchemist must solve a series of magical puzzles to find the legendary Philosopher\'s Stone before it falls into the wrong hands.',
            imdbRating: 7.2,
            imdbVotes: '350,678',
            boxOffice: '$654.9M',
            awards: 'Nominated for Best Production Design.',
            isNewRelease: false,
            isTrending: false,
            isPopular: true,
        },
        {
            title: 'Zero Point Colony',
            year: 2026,
            rated: 'PG-13',
            runtime: 142,
            genres: ['Sci-Fi', 'Drama'],
            director: 'Christopher Nolan',
            writers: ['Jonathan Nolan', 'Christopher Nolan'],
            actors: ['John David Washington', 'Cillian Murphy', 'Anne Hathaway'],
            plot: 'The first generation of humans born on Mars faces a psychological crisis as they grapple with their identity and a longing for a planet they\'ve never known.',
            imdbRating: 9.2,
            imdbVotes: 'N/A',
            boxOffice: 'N/A',
            awards: 'Awaiting release.',
            isNewRelease: true,
            isTrending: true,
            isPopular: false,
        },
        {
            title: 'Desert Bloom',
            year: 2017,
            rated: 'R',
            runtime: 122,
            genres: ['Western', 'Drama'],
            director: 'Clint Eastwood',
            writers: ['Nick Schenk'],
            actors: ['Clint Eastwood', 'Jeff Bridges', 'Michelle Pfeiffer'],
            plot: 'An aging lawman in a dying town takes on one last job: to protect a homesteader family from a ruthless cattle baron who wants their land.',
            imdbRating: 7.6,
            imdbVotes: '120,456',
            boxOffice: '$35.8M',
            awards: 'Nominated for Best Original Screenplay.',
            isNewRelease: false,
            isTrending: false,
            isPopular: false,
        },
        // Adding 20 more movies to reach the 40-50 goal.
        {
            title: 'Nightfall',
            year: 2023,
            rated: 'R',
            runtime: 108,
            genres: ['Horror', 'Thriller'],
            director: 'Ari Aster',
            writers: ['Ari Aster'],
            actors: ['Toni Collette', 'Alex Wolff', 'Milly Shapiro'],
            plot: 'A family living in an isolated cabin finds themselves terrorized by a supernatural entity that only appears after sunset.',
            imdbRating: 7.3,
            imdbVotes: '110,987',
            boxOffice: '$80.2M',
            awards: 'Winner of Best Horror Film at Sitges Film Festival.',
            isNewRelease: false,
            isTrending: false,
            isPopular: true,
        },
        {
            title: 'The Gilded Cage',
            year: 2022,
            rated: 'PG-13',
            runtime: 131,
            genres: ['Drama', 'History'],
            director: 'Joe Wright',
            writers: ['Tom Stoppard'],
            actors: ['Keira Knightley', 'Matthew Macfadyen', 'Carey Mulligan'],
            plot: 'In the opulent world of 18th-century France, a young noblewoman navigates the treacherous politics of the royal court, where love and betrayal are intertwined.',
            imdbRating: 7.4,
            imdbVotes: '95,678',
            boxOffice: '$120.3M',
            awards: 'Winner of Best Costume Design at the Academy Awards.',
            isNewRelease: false,
            isTrending: false,
            isPopular: false,
        },
        {
            title: 'Ocean\'s Whisper',
            year: 2024,
            rated: 'G',
            runtime: 94,
            genres: ['Documentary', 'Nature'],
            director: 'David Attenborough',
            writers: ['David Attenborough'],
            actors: ['Narrated by David Attenborough'],
            plot: 'An awe-inspiring journey into the deepest and most mysterious parts of our oceans, revealing newly discovered species and breathtaking underwater landscapes.',
            imdbRating: 9.3,
            imdbVotes: '80,123',
            boxOffice: 'N/A',
            awards: 'Awaiting release.',
            isNewRelease: true,
            isTrending: false,
            isPopular: false,
        },
        {
            title: 'Cybernetic Dawn',
            year: 2021,
            rated: 'R',
            runtime: 133,
            genres: ['Sci-Fi', 'Action'],
            director: 'Neill Blomkamp',
            writers: ['Neill Blomkamp', 'Terri Tatchell'],
            actors: ['Sharlto Copley', 'Dev Patel', 'Sigourney Weaver'],
            plot: 'In a future where humanity is policed by autonomous androids, a sentient AI goes rogue, forcing its creator to team up with a rebel faction to stop it.',
            imdbRating: 7.0,
            imdbVotes: '180,456',
            boxOffice: '$210.8M',
            awards: 'Nominated for Best Visual Effects.',
            isNewRelease: false,
            isTrending: false,
            isPopular: true,
        },
        {
            title: 'Heart of the Mountain',
            year: 2020,
            rated: 'PG',
            runtime: 102,
            genres: ['Adventure', 'Family'],
            director: 'Brad Bird',
            writers: ['Brad Bird'],
            actors: ['Thomasin McKenzie', 'Roman Griffin Davis', 'Scarlett Johansson'],
            plot: 'Two siblings discover a map that leads them on an epic adventure into a hidden world inside a dormant volcano, where they find mythical creatures and a lost civilization.',
            imdbRating: 7.5,
            imdbVotes: '90,123',
            boxOffice: '$150.6M',
            awards: 'People\'s Choice Award at TIFF.',
            isNewRelease: false,
            isTrending: false,
            isPopular: false,
        },
        {
            title: 'The Silent Guardian',
            year: 2023,
            rated: 'R',
            runtime: 129,
            genres: ['Action', 'Thriller'],
            director: 'Gareth Evans',
            writers: ['Gareth Evans'],
            actors: ['Iko Uwais', 'Yayan Ruhian', 'Joe Taslim'],
            plot: 'A former special forces operative living a quiet life as a librarian is forced back into action when a ruthless syndicate targets the young girl he has sworn to protect.',
            imdbRating: 7.9,
            imdbVotes: '115,789',
            boxOffice: '$98.9M',
            awards: 'Winner of Midnight Madness award at TIFF.',
            isNewRelease: false,
            isTrending: true,
            isPopular: true,
        },
        {
            title: 'Ashen Empire',
            year: 2025,
            rated: 'R',
            runtime: 170,
            genres: ['Fantasy', 'War', 'Drama'],
            director: 'Peter Jackson',
            writers: ['Fran Walsh', 'Philippa Boyens'],
            actors: ['Andy Serkis', 'Viggo Mortensen', 'Cate Blanchett'],
            plot: 'Decades after a great war, a fragile peace is shattered when a new, charismatic leader rises from the ashes of a fallen empire, seeking to conquer all lands with dark magic.',
            imdbRating: 8.9,
            imdbVotes: 'N/A',
            boxOffice: 'N/A',
            awards: 'Awaiting release.',
            isNewRelease: true,
            isTrending: true,
            isPopular: false,
        },
        {
            title: 'Solaris Rising',
            year: 2022,
            rated: 'PG-13',
            runtime: 138,
            genres: ['Sci-Fi', 'Adventure'],
            director: 'James Cameron',
            writers: ['James Cameron'],
            actors: ['Sam Worthington', 'Zoe Saldaña', 'Sigourney Weaver'],
            plot: 'On a newly terraformed planet, colonists discover a sentient ecosystem that communicates through light, but a corporate entity seeks to exploit it for its resources.',
            imdbRating: 7.8,
            imdbVotes: '650,123',
            boxOffice: '$936.7M',
            awards: 'Winner of 3 Academy Awards for Visuals and Sound.',
            isNewRelease: false,
            isTrending: false,
            isPopular: true,
        },
        {
            title: 'Code of Silence',
            year: 2019,
            rated: 'R',
            runtime: 121,
            genres: ['Crime', 'Drama', 'Thriller'],
            director: 'Martin Scorsese',
            writers: ['Steven Zaillian'],
            actors: ['Robert De Niro', 'Al Pacino', 'Joe Pesci'],
            plot: 'A mob hitman reflects on his life and the choices that led him down a path of violence and betrayal, bound by a code that demands absolute loyalty.',
            imdbRating: 7.8,
            imdbVotes: '380,456',
            boxOffice: '$9.6M (Limited Release)',
            awards: 'Nominated for 10 Academy Awards.',
            isNewRelease: false,
            isTrending: false,
            isPopular: false,
        },
        {
            title: 'The Emerald Key',
            year: 2023,
            rated: 'PG',
            runtime: 112,
            genres: ['Adventure', 'Fantasy', 'Family'],
            director: 'Wes Anderson',
            writers: ['Wes Anderson', 'Roman Coppola'],
            actors: ['Bill Murray', 'Tilda Swinton', 'Owen Wilson'],
            plot: 'A quirky family of explorers embarks on a whimsical journey through a series of enchanted lands to find a mythical key that unlocks the door to happiness.',
            imdbRating: 7.6,
            imdbVotes: '130,987',
            boxOffice: '$174.6M',
            awards: 'Nominated for Best Production Design.',
            isNewRelease: false,
            isTrending: false,
            isPopular: false,
        },
        {
            title: 'Vanguard',
            year: 2022,
            rated: 'R',
            runtime: 149,
            genres: ['Action', 'War'],
            director: 'Sam Mendes',
            writers: ['Sam Mendes', 'Krysty Wilson-Cairns'],
            actors: ['George MacKay', 'Dean-Charles Chapman', 'Mark Strong'],
            plot: 'During the height of World War I, two young soldiers are given an impossible mission: to deliver a message deep in enemy territory that will stop a deadly attack.',
            imdbRating: 8.2,
            imdbVotes: '560,123',
            boxOffice: '$384.9M',
            awards: 'Winner of 3 Academy Awards, including Best Cinematography.',
            isNewRelease: false,
            isTrending: false,
            isPopular: true,
        },
        {
            title: 'Echoes of Tomorrow',
            year: 2024,
            rated: 'PG-13',
            runtime: 135,
            genres: ['Sci-Fi', 'Drama', 'Romance'],
            director: 'Spike Jonze',
            writers: ['Spike Jonze'],
            actors: ['Joaquin Phoenix', 'Rooney Mara', 'Amy Adams'],
            plot: 'In the near future, a lonely writer develops an unlikely relationship with an advanced AI designed to meet his every need, forcing him to question the nature of love and consciousness.',
            imdbRating: 8.0,
            imdbVotes: '550,987',
            boxOffice: '$48.3M',
            awards: 'Winner of Best Original Screenplay at the Academy Awards.',
            isNewRelease: true,
            isTrending: false,
            isPopular: false,
        },
        {
            title: 'The Glass City',
            year: 2021,
            rated: 'PG-13',
            runtime: 126,
            genres: ['Sci-Fi', 'Mystery'],
            director: 'Alex Garland',
            writers: ['Alex Garland'],
            actors: ['Oscar Isaac', 'Alicia Vikander', 'Domhnall Gleeson'],
            plot: 'A detective in a utopian city built entirely of glass must solve a murder in a society where privacy is non-existent and every action is observed.',
            imdbRating: 7.7,
            imdbVotes: '500,123',
            boxOffice: '$36.9M',
            awards: 'Nominated for Best Original Screenplay.',
            isNewRelease: false,
            isTrending: false,
            isPopular: false,
        },
        {
            title: 'Ironclad',
            year: 2011,
            rated: 'R',
            runtime: 121,
            genres: ['History', 'Action', 'Drama'],
            director: 'Jonathan English',
            writers: ['Jonathan English', 'Erick Kastel'],
            actors: ['James Purefoy', 'Brian Cox', 'Paul Giamatti'],
            plot: 'In 13th-century England, a small group of Knights Templar fights to defend Rochester Castle against the tyrannical King John.',
            imdbRating: 6.9,
            imdbVotes: '110,456',
            boxOffice: '$5.8M',
            awards: 'A cult classic among history buffs.',
            isNewRelease: false,
            isTrending: false,
            isPopular: false,
        },
        {
            title: 'Serpent\'s Kiss',
            year: 2025,
            rated: 'R',
            runtime: 132,
            genres: ['Thriller', 'Fantasy', 'Horror'],
            director: 'Robert Eggers',
            writers: ['Robert Eggers', 'Sjón'],
            actors: ['Anya Taylor-Joy', 'Willem Dafoe', 'Alexander Skarsgård'],
            plot: 'In a remote 19th-century village, a young woman is accused of witchcraft after a series of mysterious and seductive deaths plague the community.',
            imdbRating: 8.5,
            imdbVotes: 'N/A',
            boxOffice: 'N/A',
            awards: 'Awaiting release.',
            isNewRelease: true,
            isTrending: true,
            isPopular: false,
        },
        {
            title: 'Final Ascent',
            year: 2018,
            rated: 'PG-13',
            runtime: 100,
            genres: ['Documentary', 'Adventure', 'Sport'],
            director: 'Jimmy Chin',
            writers: ['Elizabeth Chai Vasarhelyi'],
            actors: ['Alex Honnold', 'Tommy Caldwell', 'Jimmy Chin'],
            plot: 'Follow Alex Honnold as he becomes the first person to ever free solo climb Yosemite\'s 3,000ft high El Capitan Wall. With no ropes or safety gear, he completed arguably the greatest feat in rock climbing history.',
            imdbRating: 8.2,
            imdbVotes: '100,123',
            boxOffice: '$29.3M',
            awards: 'Winner of Best Documentary Feature at the Academy Awards.',
            isNewRelease: false,
            isTrending: false,
            isPopular: false,
        }
    ].map(movie => {
        const id = slugify(movie.title);
        return {
            ...movie,
            id,
            poster: `assets/posters/${id}.webp`,
            heroImage: `assets/hero/${id}.webp`,
            trailer: `assets/trailers/${id}.mp4`,
        };
    });

    // --- Public API ---

    /**
     * Retrieves the complete list of movies.
     * @returns {Array<object>} A copy of the movies array to prevent mutation.
     */
    const getAllMovies = () => [...movies];

    /**
     * Finds a movie by its unique ID.
     * @param {string} id - The slugified ID of the movie.
     * @returns {object|undefined} The movie object or undefined if not found.
     */
    const getMovieById = (id) => movies.find(movie => movie.id === id);

    /**
     * Retrieves movies flagged as "Trending".
     * @returns {Array<object>} An array of trending movies.
     */
    const getTrendingMovies = () => movies.filter(movie => movie.isTrending);

    /**
     * Retrieves movies flagged as "New Release".
     * @returns {Array<object>} An array of new release movies.
     */
    const getNewReleases = () => movies.filter(movie => movie.isNewRelease);

    /**
     * Retrieves movies flagged as "Popular".
     * @returns {Array<object>} An array of popular movies.
     */
    const getPopularMovies = () => movies.filter(movie => movie.isPopular);

    /**
     * Retrieves all movies belonging to a specific genre.
     * @param {string} genre - The genre to filter by (case-insensitive).
     * @returns {Array<object>} An array of movies matching the genre.
     */
    const getMoviesByGenre = (genre) => {
        const lowerCaseGenre = genre.toLowerCase();
        return movies.filter(movie =>
            movie.genres.some(g => g.toLowerCase() === lowerCaseGenre)
        );
    };

    /**
     * Retrieves a list of all unique genres available.
     * @returns {string[]} An array of unique genre strings.
     */
    const getAllGenres = () => {
        const allGenres = movies.flatMap(movie => movie.genres);
        return [...new Set(allGenres)].sort();
    };

    return {
        getAllMovies,
        getMovieById,
        getTrendingMovies,
        getNewReleases,
        getPopularMovies,
        getMoviesByGenre,
        getAllGenres,
    };
})();